Enchants:
  WATER_WORKER:
    DisplayName: '&6&lAqua Affinity'
    Description: '&6Speeds up how fast you can mine blocks underwater'
    MinLevel: 1
    MaxLevel: 1
    Items:
      - 'Helmet'
  DAMAGE_ARTHROPODS:
    DisplayName: '&6&lBane of Arthropods'
    Description: '&6Increases attack damage against arthropods'
    MinLevel: 1
    MaxLevel: 5
    Items:
      - 'Sword'
      - 'Axe'
  PROTECTION_EXPLOSIONS:
    DisplayName: '&6&lBlast Protection'
    Description: '&6Reduces blast and explosion damage'
    MinLevel: 1
    MaxLevel: 4
    Items:
      - 'Armor'
  DEPTH_STRIDER:
    DisplayName: '&6&lBlast Protection'
    Description: '&6Speeds up how fast you can move underwater'
    MinLevel: 1
    MaxLevel: 3
    Items:
      - 'Boots'
  DIG_SPEED:
    DisplayName: '&6&lEfficiency'
    Description: '&6Increases how fast you can mine'
    MinLevel: 1
    MaxLevel: 5
    Items:
      - 'Tools'
  PROTECTION_FALL:
    DisplayName: '&6&lFeather Falling'
    Description: '&6Reduces fall and teleportation damage'
    MinLevel: 1
    MaxLevel: 4
    Items:
      - 'Boots'
  FIRE_ASPECT:
    DisplayName: '&6&lFire Aspect'
    Description: '&6Sets target on fire'
    MinLevel: 1
    MaxLevel: 2
    Items:
      - 'Sword'
  PROTECTION_FIRE:
    DisplayName: '&6&lFire Protection'
    Description: '&6Reduces damage caused by fire and lava'
    MinLevel: 1
    MaxLevel: 4
    Items:
      - 'Armor'
  ARROW_FIRE:
    DisplayName: '&6&lFlame'
    Description: '&6Turns arrows into flaming arrows'
    MinLevel: 1
    MaxLevel: 1
    Items:
      - 'Bow'
  ARROW_INFINITE:
    DisplayName: '&6&lInfinity'
    Description: '&6Shoots an infinite amount of arrows'
    MinLevel: 1
    MaxLevel: 1
    Items:
      - 'Bow'
  KNOCKBACK:
    DisplayName: '&6&lKnockback'
    Description: '&6Increases knockback dealt (enemies repel backwards)'
    MinLevel: 1
    MaxLevel: 2
    Items:
      - 'Sword'
  LOOT_BONUS_MOBS:
    DisplayName: '&6&Looting'
    Description: '&6Increases amount of loot dropped when mob is killed'
    MinLevel: 1
    MaxLevel: 3
    Items:
      - 'Sword'
  LUCK:
    DisplayName: '&6&Luck of the Sea'
    Description: '&6Increases chances of catching valuable items'
    MinLevel: 1
    MaxLevel: 3
    Items:
      - 'Fishing Rod'
  LURE:
    DisplayName: '&6&lLure'
    Description: '&6Increases the rate of fish biting your hook'
    MinLevel: 1
    MaxLevel: 3
    Items:
      - 'Fishing Rod'
  ARROW_DAMAGE:
    DisplayName: '&6&lPower'
    Description: '&6Increases damage dealt by bow'
    MinLevel: 1
    MaxLevel: 5
    Items:
      - 'Bow'
  PROTECTION_PROJECTILE:
    DisplayName: '&6&lProjectile Protection'
    Description: '&6Reduces projectile damage (arrows, fireballs, fire charges)'
    MinLevel: 1
    MaxLevel: 4
    Items:
      - 'Armor'
  PROTECTION_ENVIRONMENTAL:
    DisplayName: '&6&lProtection'
    Description: '&6General protection against attacks, fire, lava, and falling'
    MinLevel: 1
    MaxLevel: 4
    Items:
      - 'Armor'
  ARROW_KNOCKBACK:
    DisplayName: '&6&lPunch'
    Description: '&6Increases knockback dealt (enemies repel backwards)'
    MinLevel: 1
    MaxLevel: 2
    Items:
      - 'Bow'
  OXYGEN:
    DisplayName: '&6&lRespiration'
    Description: '&6Extends underwater breathing (see better underwater)'
    MinLevel: 1
    MaxLevel: 2
    Items:
      - 'Helmet'
  DAMAGE_ALL:
    DisplayName: '&6&lSharpness'
    Description: '&6Increases attack damage dealt to mobs'
    MinLevel: 1
    MaxLevel: 5
    Items:
      - 'Sword'
      - 'Axe'
  SILK_TOUCH:
    DisplayName: '&6&lSilk Touch'
    Description: '&6Mines blocks themselves (fragile items)'
    MinLevel: 1
    MaxLevel: 1
    Items:
      - 'Tools'
  DAMAGE_UNDEAD:
    DisplayName: '&6&lSmite'
    Description: '&6Increases attack damage against undead mobs'
    MinLevel: 1
    MaxLevel: 5
    Items:
      - 'Sword'
  THORNS:
    DisplayName: '&6&lT horns'
    Description: '&6Causes damage to attackers'
    MinLevel: 1
    MaxLevel: 3
    Items:
      - 'Armor'
  DURABILITY:
    DisplayName: '&6&lUnbreaking'
    Description: '&6Increases durability of item'
    MinLevel: 1
    MaxLevel: 3
    Items:
      - 'Sword'
      - 'Bow'
      - 'Fishing Rod'
      - 'Tools'
      - 'Armor'

Item Lore:
  - '&fLevel: &6{level}'
  - '&r'
  - '{description}'
  - '&r'
  - '&6&nDrag & Drop &7to enchant your item'

Usage: '&fUsage: &6/enchantbook give [player] [enchant] [level] [quantity]'
InvalidPlayer: '&cThe targeted player is not online or does not exist'
InvalidEnchant: '&cThe provided enchant name is does not target a valid vanilla enchant'
ArgumentNotANumber: '&cOne of your arguments is not a number. Please change it to a number'
LevelOutOfBounds: '&cThe level argument is out of bounds'
QuantityOutOfBounds: '&cThe quantity argument is out of bounds'
EnchantBooksAdded: '&aThe enchants book specified were added to the players inventory'
EnchantAlreadyApplied: '&cThere is already an enchant with the maximum level on this item!'
EnchantApplied: '&aThe enchant was applied with success!'
