name: BlazedEnchants
version: ${project.version}
main: me.cristike.enchants.Main
api-version: 1.8
authors: [ Cristike ]
commands:
  enchantbook:
    description: Give a enchant book to a player
    permission: enchantbook.give